document.writeln("<ul>");
document.writeln("			    <li>");
document.writeln("			    	<a href=\"../../home.html\" class=\"active\"><span>主页</span></a>");
document.writeln("			    </li>");
document.writeln("			    <li>");
document.writeln("			    	<a href=\"#\"><span>营销管理</span></a>");
document.writeln("			    	<ul>");
document.writeln("                        <li><a href=\"../sales/chanceList.html\">销售机会管理</a></li>");
document.writeln("			    		<li><a href=\"../sales/customerPlan-sell manager/chanceList.html\">客户开发计划管理(主管)</a></li>");
document.writeln("                        <li><a href=\"../sales/customerPlan-client manager/designatedChanceList.html\">客户开发计划管理(客户经理)</a></li>");
document.writeln("                        <!-- 客户开发计划管理需要判断登录人的身份后分别根据不同角色跳转不同的页面 -->");
document.writeln("                    </ul>");
document.writeln("			    </li>");
document.writeln("                ");
document.writeln("			    <li>");
document.writeln("			    	<a href=\"#\"><span>客户管理</span></a>");
document.writeln("			    	<ul>");
document.writeln("			    		<li><a href=\"../customer/customerInfo/customerList.html\">客户列表</a></li>");
document.writeln("			    		<li><a href=\"../customer/customerLoss/clientListForYujing-XSZG.html\">客户流失预警(主管)</a></li>");
document.writeln("                        <li><a href=\"../customer/customerLoss/clientListForYujing-KHJL.html\">客户流失预警(客户经理)</a></li>");
document.writeln("                        <!-- 客户流失预警列表需要判断登录人的身份后分别根据不同角色跳转不同的页面 -->");
document.writeln("                        <li><a href=\"../customer/customerLoss/clientLiushiList.html\">流失客户列表</a></li>");
document.writeln("			    	</ul>");
document.writeln("			    </li>");
document.writeln("                ");
document.writeln("			    <li>");
document.writeln("			    	<a href=\"#\"><span>服务管理</span></a>");
document.writeln("			    	<ul>");
document.writeln("			    		<li><a href=\"../business/bussinessList.html\" >服务列表</a></li>");
document.writeln("                        <li><a href=\"../business/bussinessProcessList.html\" >服务处理</a></li>");
document.writeln("			    		<li><a href=\"../business/bussinessFeedBackList.html\" >服务反馈</a></li>");
document.writeln("			    		<li><a href=\"../business/bussinessFileList.html\" >服务归档</a></li>");
document.writeln("			    	</ul>  ");
document.writeln("			    </li>");
document.writeln("                ");
document.writeln("			    <li>");
document.writeln("			    	<a href=\"#\"><span>统计报表</span></a>");
document.writeln("			    	<ul>");
document.writeln("			    		<li><a href=\"../statistic/cusCtributeAnalyze.html\">客户贡献分析</a></li>");
document.writeln("			    		<li><a href=\"../statistic/cusFormAnalyze.html\">客户构成分析</a></li>");
document.writeln("			    		<li><a href=\"../statistic/cusServiceAnalyze.html\">客户服务分析</a></li>");
document.writeln("			    		<li><a href=\"../statistic/cusLoseAnalyze.html\">客户流失分析</a></li>");
document.writeln("			    	</ul>");
document.writeln("			    </li>");
document.writeln("                ");
document.writeln("			    <li>");
document.writeln("			    	<a href=\"#\"><span>基础数据</span></a>");
document.writeln("			    	<ul>");
document.writeln("			    		<li><a href=\"#\">数据字典管理</a></li>");
document.writeln("			    		<li><a href=\"#\">查询产品信息</a></li>");
document.writeln("			    		<li><a href=\"#\">查询库存</a></li>");
document.writeln("			    	</ul>");
document.writeln("			    </li>");
document.writeln("			    <li>");
document.writeln("			    	<a href=\"#\"><span>用户角色管理</span></a>");
document.writeln("			    	<ul>");
document.writeln("			    		<li><a href=\"#\">账号信息管理</a></li>");
document.writeln("			    		<li><a href=\"#\">账号创建</a></li>");
document.writeln("			    		<li><a href=\"#\">账号冻结</a></li>");
document.writeln("			    	</ul>");
document.writeln("			    </li>");
document.writeln("			</ul>");